services:
  ai-tester:
    build: .
    working_dir: /app
    env_file: .env
    volumes:
      - ./tests:/app/tests
      - ./captures:/app/captures
      - ./reports:/app/reports
    entrypoint: ["python", "main.py"]
    command: ["--help"]